/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData ai = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData paint = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData money = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData food = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData recycle = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData map = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cup = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData college_graduation =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData tractor_icon = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData finance = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData e = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData artificial_intelligence =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData projektmanagement =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData health_5fe9bcc602d060755a6375608845b192 =
      IconData(0xe80d, fontFamily: _kFontFam);
}
